---
# This assigns a PR to its author
addAssignees: author

addReviewers: true

useReviewGroups: true

reviewGroups:
  # The default reviewers
  defaults:
    - maintainers

  groups:
    maintainers:
      - OrlinVasilev
#      - OrlinVasilev1
#      - OrlinVasilev2

    community:
      - OrlinVasilev

#files:
#  'site/**':
#    - tech-writer
#  '**/*.md':
#    - community
#  # Technical design requests are ".md" files but should
#  # be reviewed by maintainers
#  '/design/**':
#    - maintainers

options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: true
  number_of_reviewers: 2
